FROM nginx
# FROM httpd

MAINTAINER Glenn Dayton

#COPY nginx.conf /etc/nginx/nginx.conf
# COPY httpd.conf /usr/local/apache2/conf/httpd.conf
# COPY ./dist/index.html /usr/share/nginx/html

VOLUME /Users/gdayton/Documents/docker-compose-tutorial/angular-app/dist:/usr/share/nginx/html
# VOLUME /Users/gdayton/Documents/eskimo/angular-app/dist:/usr/local/apache2/htdocs
#COPY ./dist /usr/local/apache2/htdocs
#COPY ./dist /usr/share/nginx/html

EXPOSE 80